"""create users table

Revision ID: 38076070a0c1
Revises: 5c2cd1506fe8
Create Date: 2025-12-02 16:01:32.705356

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38076070a0c1"
down_revision: Union[str, None] = "5c2cd1506fe8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("status", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "status")
    # ### end Alembic commands ###
