"""create order_reports

Revision ID: 56c01830e8cf
Revises: 38076070a0c1
Create Date: 2025-12-16 07:16:08.809961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c01830e8cf'
down_revision: Union[str, None] = '38076070a0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_reports',
    sa.Column('report_at', sa.Date(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('count_product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_at', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_reports')
    # ### end Alembic commands ###
