"""empty message

Revision ID: 8de39c2de269
Revises: 12f5ea5b4b62
Create Date: 2025-10-07 23:27:52.627993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de39c2de269'
down_revision: Union[str, None] = '12f5ea5b4b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('products_productname_key', 'products', type_='unique')
    op.create_unique_constraint(None, 'products', ['name'])
    op.drop_column('products', 'productname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('productname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.create_unique_constraint('products_productname_key', 'products', ['productname'])
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
